[workspace]

exclude = [".github/workflows/scripts/build_directory"]

members = [
    "datastructures",
    "math",
    "programs/guess_game",
    "time",
    "utils",
    "basics",
    "algorithms",
    "strings",
    "programs/restaurant",
    "puzzles",
    "design"
]
